### ISSUE TITLE
Null Pointer Exception trying to build a joint project

### ISSUE THREAD

**Issue by jeacott1** [groovy/GMavenPlus#195] opened 2021-08-31 04:25 UTC
Null Pointer Exception trying to build a joint project
groovy 2.4.8
gmavenplus-plugin 1.12.1

```
    <plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <version>1.12.1</version>
        <executions>
          <execution>
            <goals>
              <goal>addSources</goal>
              <goal>addTestSources</goal>
              <goal>compileTests</goal>
              <goal>compile</goal>     
              <goal>generateTestStubs</goal>
              <goal>generateStubs</goal>
              <goal>removeStubs</goal>
              <goal>removeTestStubs</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
         <testSources>
            <testSource>
              <includes>
                 <include>**/*.groovy</include>
              </includes>
            </testSource>
          </testSources>
        </configuration>
      </plugin>
```

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.12.1:generateTestStubs (default) on project cclas-test-automation: Execution default of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.12.1:generateTestStubs failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.12.1:generateTestStubs (default) on project cclas-test-automation: Execution default of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.12.1:generateTestStubs failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.12.1:generateTestStubs failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.NullPointerException
    at java.io.File.<init> (File.java:277)
    at org.apache.maven.shared.model.fileset.util.FileSetManager.scan (FileSetManager.java:640)
    at org.apache.maven.shared.model.fileset.util.FileSetManager.getIncludedFiles (FileSetManager.java:190)
    at org.codehaus.gmavenplus.mojo.AbstractGroovySourcesMojo.getTestFiles (AbstractGroovySourcesMojo.java:78)
    at org.codehaus.gmavenplus.mojo.GenerateTestStubsMojo.execute (GenerateTestStubsMojo.java:79)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)

```

**Comment by keeganwitt** [comment] 2021-09-02 02:13
I'm having trouble reproducing this. I thought maybe it'd happen in a project that didn't have any groovy files in it, but that wasn't the issue.  What version of Maven are you using?

You probably don't need the `<testSources>` anyway. But one thing you might try if you want to have it is to also specify a directory to apply the pattern to, like
```xml
<testSources>
    <testSource>
        <directory>${project.basedir}/src/test/groovy</directory>
        <includes>
            <include>**/*.groovy</include>
        </includes>
    </testSource>
</testSources>
```
I'm not sure if that's the cause (I haven't been able to reproduce it), but might be something to try.

**Comment by jeacott1** [comment] 2021-09-02 03:02
@keeganwitt maven 3.6.3, Java version: 1.8.0_202
thousands of groovy files, and a few java files mixed in.
I haven't seen this issue before but its incredibly consistent with this project.

I've had to resort to using the maven ant plugin to build this project for the moment, which is working - the maven-eclipse groovy plugin doesn't come close.

**Comment by keeganwitt** [comment] 2021-12-16 02:40
Closing issue for now, but if you can provide information on how to reproduce, I'll reopen.

**Closed by keeganwitt** 2021-12-16 02:40 UTC
